use grocery_store_management;
show tables;


-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.


-- How many unique customers have placed orders?
SELECT 
    COUNT(DISTINCT (cust_id)) unique_customers
FROM
    orders;


-- Which customers have placed the highest number of orders?
SELECT 
    c.cust_id, c.cust_name, COUNT(o.ord_id) count
FROM
    customers c
        INNER JOIN
    orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id , c.cust_name
ORDER BY count DESC
LIMIT 15;



-- select cust_name from customers where cust_name='chetan naidu';
select * from customers where  cust_name='chetan naidu';


-- What is the total and average purchase value per customer?
SELECT 
	c.cust_id,
    c.cust_name,
    SUM(od.total_price) sum,
    AVG(od.total_price) avg
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id;



-- Who are the top 5 customers by total purchase amount?
SELECT 
    c.cust_id, c.cust_name, SUM(od.total_price) total_purchase
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id
ORDER BY total_purchase DESC
LIMIT 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- How many products exist in each category?

SELECT 
    c.cat_name, COUNT(p.prod_id) product_count
FROM
    categories c
        JOIN
    products p ON p.cat_id = c.cat_id
GROUP BY cat_name;



-- What is the average price of products by category?
SELECT 
    c.cat_name, AVG(p.price) avg_price
FROM
    categories c
        JOIN
    products p ON p.cat_id = c.cat_id
GROUP BY c.cat_name;



-- Which products have the highest total sales volume (by quantity)?
SELECT 
    p.prod_name, SUM(od.quantity) total_sales
FROM
    products p
        LEFT JOIN
    order_details od ON p.prod_id = od.prod_id
GROUP BY prod_name
ORDER BY total_sales DESC
LIMIT 1;



-- What is the total revenue generated by each product?

SELECT 
    p.prod_name, SUM(od.quantity * od.each_price) total_sales
FROM
    products p
        LEFT JOIN
    order_details od ON p.prod_id = od.prod_id
GROUP BY prod_name;



-- How do product sales vary by category and supplier?
-- ?????????
SELECT 
    c.cat_name, s.sup_name, SUM(od.total_price) sales
FROM
    categories c
        JOIN
    products p ON c.cat_id = p.cat_id
        JOIN
    order_details od ON od.prod_id = p.prod_id
        JOIN
    supplier s ON s.sup_id = p.sup_id
GROUP BY c.cat_name , s.sup_name
ORDER BY cat_name , sales DESC;
select * from order_details;




-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- How many orders have been placed in total?
SELECT 
    COUNT(ord_id)
FROM
    orders;
    
    
-- What is the average value per order?
select avg(each_price) avg from order_details;



-- On which dates were the most orders placed?
SELECT 
    order_date, COUNT(o.ord_id) count
FROM
    orders o
GROUP BY order_date
ORDER BY count DESC
LIMIT 1;



-- What are the monthly trends in order volume and revenue?
SELECT 
    LEFT(o.order_date, 1) month,
    COUNT(o.ord_id) volume,
    SUM(od.total_price) sales
FROM
    orders o
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;




-- How do order patterns vary across weekdays and weekends?
set Sql_safe_updates=0;
alter table orders add column date_converted date;
UPDATE orders 
SET 
    date_converted = STR_TO_DATE(order_date, '%c/%e/%Y');
SELECT 
    DAYNAME(date_converted) weekday,
    MONTHNAME(date_converted) month,
    COUNT(ord_id) orders
FROM
    orders
GROUP BY weekday , month
ORDER BY weekday , month;




-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- How many suppliers are there in the database?
SELECT 
    COUNT(*)
FROM
    supplier;



-- Which supplier provides the most products?
SELECT 
    sup_name, COUNT(DISTINCT (prod_id)) count
FROM
    supplier s
        JOIN
    products p ON s.sup_id = p.sup_id
GROUP BY sup_name
ORDER BY count DESC;



-- What is the average price of products from each supplier?
SELECT 
    s.sup_name, AVG(p.price) avg
FROM
    supplier s
        JOIN
    products p ON s.sup_id = p.sup_id
GROUP BY sup_name
ORDER BY avg DESC;



-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.sup_id, s.sup_name, SUM(od.total_price) revenue
FROM
    supplier s
        JOIN
    products p ON p.sup_id = s.sup_id
        JOIN
    order_details od ON od.prod_id = p.prod_id
GROUP BY sup_id
ORDER BY revenue DESC
LIMIT 1;



-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- How many employees have processed orders?
SELECT 
    COUNT(DISTINCT emp_id) count
FROM
    employees;




select * from orders;
select * from order_details;



-- Which employees have handled the most orders?
SELECT 
    emp_name, COUNT(o.ord_id) count
FROM
    employees
        JOIN
    orders o ON employees.emp_id = o.emp_id
GROUP BY emp_name
ORDER BY count DESC
LIMIT 5;



-- What is the total sales value processed by each employee?
SELECT 
    emp_name, COUNT(od.ord_id) total_sales
FROM
    employees e
        JOIN
    orders o ON e.emp_id = o.emp_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY emp_name
ORDER BY total_sales DESC;



-- What is the average order value handled per employee?
SELECT 
    e.emp_id,
    e.emp_name,
    SUM(od.total_price) / COUNT(DISTINCT o.ord_id) avg_sales
FROM
    employees e
        JOIN
    orders o ON e.emp_id = o.emp_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id
ORDER BY avg_sales DESC;




-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- What is the relationship between quantity ordered and total price?
SELECT 
    quantity, COUNT(ord_id) count, AVG(total_price) avg
FROM
    order_details
GROUP BY quantity
ORDER BY quantity;



-- What is the average quantity ordered per product?
SELECT 
    prod_name, COUNT(o.ord_id) count, AVG(o.quantity) avg
FROM
    products p
        JOIN
    order_details o ON p.prod_id = o.prod_id
GROUP BY prod_name
ORDER BY avg;



-- How does the unit price vary across products and orders?
SELECT 
    p.prod_id, p.prod_name, o.each_price, COUNT(o.ord_id) count
FROM
    products p
        JOIN
    order_details o ON o.prod_id = p.prod_id
GROUP BY p.prod_id , o.each_price;
